#!/bin/bash
sudo /usr/sbin/create-munge-key 
sudo chmod 700 /etc/munge/
sudo chmod 711 /var/lib/munge/
sudo chmod 700 /var/log/munge/
sudo mkdir /run/munge
sudo chmod 755 /var/run/munge/
sudo chmod 700 /var/log
sudo chown 1000 /var/log/munge
sudo chown 1000 /var/log
sudo chown 1000 /run/munge/
sudo chown 1000 /var/lib/munge
sudo chown 1000 /etc/munge/munge.key 
sudo chown 1000 /etc/munge
